/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.softwarica.wetrack.views;

import edu.softwarica.wetrack.models.User;

/**
 *
 * @author Prashanna
 */
public class DashboardFrame extends javax.swing.JFrame {
  
    public static User currentUser;
    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame(User currentUser) {
        initComponents();
        this.currentUser = currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        projectMenu = new javax.swing.JMenu();
        viewProjectsMenuItem = new javax.swing.JMenuItem();
        addProjectMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        membersMenu = new javax.swing.JMenu();
        viewMemMenuItem = new javax.swing.JMenuItem();
        taskMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        edit_profile = new javax.swing.JMenuItem();
        edit_project = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 0));

        projectMenu.setText("Project");

        viewProjectsMenuItem.setText("View Projects");
        viewProjectsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProjectsMenuItemActionPerformed(evt);
            }
        });
        projectMenu.add(viewProjectsMenuItem);

        addProjectMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        addProjectMenuItem.setText("Add Project");
        addProjectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectMenuItemActionPerformed(evt);
            }
        });
        projectMenu.add(addProjectMenuItem);
        projectMenu.add(jSeparator1);

        exitMenuItem.setText("Logout");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        projectMenu.add(exitMenuItem);

        jMenuBar1.add(projectMenu);

        membersMenu.setText("Members");

        viewMemMenuItem.setText("View Member");
        viewMemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMemMenuItemActionPerformed(evt);
            }
        });
        membersMenu.add(viewMemMenuItem);

        jMenuBar1.add(membersMenu);

        taskMenu.setText("Tasks");
        jMenuBar1.add(taskMenu);

        jMenu1.setText("Edit");

        edit_profile.setText("Edit Profile");
        edit_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_profileActionPerformed(evt);
            }
        });
        jMenu1.add(edit_profile);

        edit_project.setText("Edit Project");
        edit_project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_projectActionPerformed(evt);
            }
        });
        jMenu1.add(edit_project);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        LoginFrame login = new LoginFrame();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void addProjectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectMenuItemActionPerformed
        // TODO add your handling code here:
        final AddProject addProjectdialog = new AddProject(currentUser,new javax.swing.JFrame(), true);
        addProjectdialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                addProjectdialog.dispose();
            }
        });
//        addProjectdialog.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/asn/mcq/bir/images/addmcq.png")));
        addProjectdialog.setLocationRelativeTo(this);
        addProjectdialog.setVisible(true);
    }//GEN-LAST:event_addProjectMenuItemActionPerformed

    private void viewMemMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMemMenuItemActionPerformed
        // TODO add your handling code here:
        this.setContentPane(new ViewMembers());
        this.validate();
    }//GEN-LAST:event_viewMemMenuItemActionPerformed

    private void viewProjectsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProjectsMenuItemActionPerformed
        // TODO add your handling code here:
         this.setContentPane(new ViewProject());
        this.validate();
    }//GEN-LAST:event_viewProjectsMenuItemActionPerformed

    private void edit_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_profileActionPerformed
        // TODO add your handling code here:
        
        EditProfile editProfile = new EditProfile(currentUser);
        editProfile.setVisible(true);
    }//GEN-LAST:event_edit_profileActionPerformed

    private void edit_projectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_projectActionPerformed
        // TODO add your handling code here:
        EditProject editproject = new EditProject();
        editproject.setVisible(true);
        
    }//GEN-LAST:event_edit_projectActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addProjectMenuItem;
    private javax.swing.JMenuItem edit_profile;
    private javax.swing.JMenuItem edit_project;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu membersMenu;
    private javax.swing.JMenu projectMenu;
    private javax.swing.JMenu taskMenu;
    private javax.swing.JMenuItem viewMemMenuItem;
    private javax.swing.JMenuItem viewProjectsMenuItem;
    // End of variables declaration//GEN-END:variables
}
